config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  collection :string
#  title      :string
#  model      :string
#  designer   :string
#  year       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord
  validates :collection, presence: true
  validates :title, presence: true
  # validates :model, presence: true
  validates :designer, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params.require(:product).permit(:collection, :title, :model, :designer, :year))
    if @product.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "Your post has been deleted"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pricelist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h3>Products</h3>
<% @products.each do |product| %>
  <div class="product">
    <h4><%= product.collection%></h4>
    <p><%= link_to product.title, product %> - <%= product.model%><br>
    <%= product.designer %>, <%= product.year %></p>
  </div>
  <p><%= link_to "Delete", product, :confirm => "Are you sure?", :method => :delete %></p>
  <hr>
<% end %>
<p><%= paginate @products %></p>
<p><%= link_to "Add a product", new_product_path %></p>

app/views/products/new.html.erb
<%= simple_form_for @product do |form| %>
  <%= form.input :collection, label: "Product Collection" %>
  <%= form.input :title, label: "Product Title" %>
  <%= form.input :model, label: "Model" %>
  <%= form.input :designer, label: "Product Designer" %>
  <%= form.input :year, label: "Design Year" %>
  <%= form.button :submit %>
<% end %>

app/views/products/show.html.erb
<h3><%= @product.title %></h3>